backend:
  name: github
  repo: owner/repo
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: menu
    label: Menu
    files:
      - file: "src/data/menu.json"
        label: "Menu Items"
        name: items
        fields:
          - name: items
            label: Items
            widget: list
            fields:
              - { name: title, label: Title, widget: string }
              - { name: description, label: Description, widget: string }
              - { name: price, label: Price, widget: string }
              - { name: category, label: Category, widget: string }
